package org.example.Instruction;

public enum InstructionTypes {
    START_EXPERIENCE,
    STOP_EXPERIENCE,
    PAUSE_EXPERIENCE,
    RESUME_EXPERIENCE,
    INCREASE_VOLUME,
    DECREASE_VOLUME,
    STOP_SOUND,
    PLAY_SOUND,
    MUTE,
    FULL_VOLUME,
    INCREASE_BRIGHTNESS,
    DECREASE_BRIGHTNESS,
    BLINDNESS,
    FULL_LIGTH,
    CHANGE_SCENARIO,
    BACK_TO_MENU;
}
